FROM flink:1.18-scala_2.12

RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev curl net-tools procps && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install apache-flink==1.18.0