# Start from the official Flink image
FROM flink:1.18-scala_2.12

# Install Python 3 and pip
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Map 'python' to 'python3' so Flink finds it easily
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install the PyFlink library (must match the Flink version!)
RUN pip3 install apache-flink==1.18.0