apiVersion: 1

datasources:
  - name: Cassandra
    type: hadoesarchitect-cassandra-datasource
    access: proxy
    url: cassandra:9042
    isDefault: true
    jsonData:
      keyspace: system
      user: cassandra
    secureJsonData:
      password: cassandra
