apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    url: cassandra:9042
    isDefault: true
    jsonData:
      keyspace: taasim
      user: cassandra
      consistency: ONE
    secureJsonData:
      password: cassandra
